import java.awt.*;
import javax.swing.*;
public class CalculatorSimple {
    private JFrame fr;
    private JPanel pn1;
    private JPanel pn2;
    private JButton bn1;
    private JButton bn2;
    private JButton bn3;
    private JButton bn4;
    private JButton bn5;
    private JButton bn6;
    private JButton bn7;
    private JButton bn8;
    private JButton bn9;
    private JButton bn10;
    private JButton bn11;
    private JButton bn12;
    private JButton bn13;
    private JButton bn14;
    private JButton bn15;
    private JButton bn16;
    private JTextField tf;
    public CalculatorSimple(){
        fr = new JFrame("My Calculator");
        pn1 = new JPanel();
        pn2 = new JPanel();
        bn1 = new JButton("7");
        bn2 = new JButton("8");
        bn3 = new JButton("9");
        bn4 = new JButton("+");
        bn5 = new JButton("4");
        bn6 = new JButton("5");
        bn7 = new JButton("6");
        bn8 = new JButton("-");
        bn9 = new JButton("1");
        bn10 = new JButton("2");
        bn11 = new JButton("3");
        bn12 = new JButton("x");
        bn13 = new JButton("0");
        bn14 = new JButton("c");
        bn15 = new JButton("=");
        bn16 = new JButton("/");
        tf = new JTextField();
        pn1.setLayout(new GridLayout(1, 1));
        pn1.add(tf);
        pn2.setLayout(new GridLayout(4, 4));
        pn2.add(bn1);
        pn2.add(bn2);
        pn2.add(bn3);
        pn2.add(bn4);
        pn2.add(bn5);
        pn2.add(bn6);
        pn2.add(bn7);
        pn2.add(bn8);
        pn2.add(bn9);
        pn2.add(bn10);
        pn2.add(bn11);
        pn2.add(bn12);
        pn2.add(bn13);
        pn2.add(bn14);
        pn2.add(bn15);
        pn2.add(bn16);
        fr.setLayout(new BorderLayout());
        fr.add(pn1, BorderLayout.NORTH);
        fr.add(pn2);
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.pack();
        fr.setVisible(true);
    }
    public static void main(String[] args) {
        new CalculatorSimple();
    }
}
